### ISSUE TITLE
Fail to train on my own dataset

### ISSUE THREAD

**Issue by liang1h** [DeepXuan/Dn-Dp#1]
All parameters are set right, and can run on the test dataset. When running on my own dataset, the error is:

```
Traceback (most recent call last):
  File "denoising.py", line 93, in <module>
    diffusion = Model.create_model(model_cfg)
  File "/mnt/code/Dn-Dp/model/__init__.py", line 7, in create_model
    m = M(opt)
  File "/mnt/code/Dn-Dp/model/model.py", line 42, in __init__
    self.load_network1()  # train: load_network; val: load_network1
  File "/mnt/code/Dn-Dp/model/model.py", line 188, in load_network1
    load_path), strict=(not self.opt['model']['finetune_norm']))
  File "/root/miniconda3/envs/myconda/lib/python3.7/site-packages/torch/serialization.py", line 593, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "/root/miniconda3/envs/myconda/lib/python3.7/site-packages/torch/serialization.py", line 762, in _legacy_load
    magic_number = pickle_module.load(f, **pickle_load_args)
EOFError: Ran out of input
```

If change `finetune_norm` to `true`, the error is:

```
Traceback (most recent call last):
  File "denoising.py", line 93, in <module>
    diffusion = Model.create_model(model_cfg)
  File "/mnt/code/Dn-Dp/model/__init__.py", line 7, in create_model
    m = M(opt)
  File "/mnt/code/Dn-Dp/model/model.py", line 40, in __init__
    optim_params, lr=opt['train']["optimizer"]["lr"])
  File "/root/miniconda3/envs/myconda/lib/python3.7/site-packages/torch/optim/adam.py", line 48, in __init__
    super(Adam, self).__init__(params, defaults)
  File "/root/miniconda3/envs/myconda/lib/python3.7/site-packages/torch/optim/optimizer.py", line 50, in __init__
    raise ValueError("optimizer got an empty parameter list")
ValueError: optimizer got an empty parameter list
```

**Comment by DeepXuan** [comment]
Sorry for that. I will organize and release the training code as soon as I complete the major revision of this paper. This may take a few weeks.

**Comment by jjjjjgggj** [comment]
冒昧问一下作者，请问什么时候能看到您上传训练代码以及训练的数据集？

**Comment by Leezus7** [comment]
requirement for training script too  thanks

**Comment by DeepXuan** [comment]
> 冒昧问一下作者，请问什么时候能看到您上传训练代码以及训练的数据集？

请再等一下。还在做对比实验。大概圣诞节前会大修完放出代码。

**Comment by DeepXuan** [comment]
> requirement for training script too thanks

Please wait for a few weeks. Still revising. The codes will be released before Christmas.

**Comment by Leezus7** [comment]
> > requirement for training script too thanks
> 
> Please wait for a few weeks. Still revising. The codes will be released before Christmas.

Thank you so much, and best wishes. ovo
